import { defaultGameConfig } from "@/lib/game-config";
import type { Match, MatchScoutEntry, PitScoutEntry, Team } from "@/lib/types";

export const event = {
  id: "2026fma",
  key: "2026fma",
  name: "FIRST Mid-Atlantic REBUILT District",
  location: "New Jersey / Pennsylvania / Delaware",
  startsAt: "2026-03-06",
  endsAt: "2026-03-08",
  gameConfig: defaultGameConfig
};

const team = (number: number, name: string, city: string, state: string): Team => ({
  number,
  name,
  city,
  state,
  strengths: ["needs scouting"],
  weaknesses: ["needs scouting"],
  strategyNotes: "Collect event-specific match and pit data before assigning a final role."
});

export const teams: Team[] = [
  { ...team(11, "MORT", "Flanders", "New Jersey"), strengths: ["home-team familiarity", "driver practice", "systems knowledge"], weaknesses: ["verify 2026 robot data at event"], strategyNotes: "Primary team profile. Keep pit notes, match clips, and reliability flags current for drive-team planning." },
  team(25, "Raider Robotix", "North Brunswick", "New Jersey"),
  team(41, "RoboWarriors", "Warren", "New Jersey"),
  team(56, "R.O.B.B.E.", "Bound Brook", "New Jersey"),
  team(75, "RoboRaiders", "Hillsborough", "New Jersey"),
  team(87, "Diablo", "Mount Holly", "New Jersey"),
  team(102, "The Gearheads", "Somerville", "New Jersey"),
  team(103, "Cybersonics", "Kintnersville", "Pennsylvania"),
  { ...team(193, "MORT Beta", "Flanders", "New Jersey"), strengths: ["program familiarity"], weaknesses: ["verify event role"], strategyNotes: "Track separately from MORT for assignment and data quality." },
  team(203, "SOUPERBOTS", "Sicklerville", "New Jersey"),
  team(204, "Eastern Robotic Vikings", "Voorhees", "New Jersey"),
  team(219, "Team Impact", "Washington", "New Jersey"),
  team(222, "Tigertrons", "Tunkhannock", "Pennsylvania"),
  team(223, "Xtreme Heat", "Wanaque", "New Jersey"),
  team(272, "Cyber Crusaders", "Lansdale", "Pennsylvania"),
  team(293, "SPIKE", "Pennington", "New Jersey"),
  team(303, "The T.E.S.T. Team", "Bridgewater", "New Jersey"),
  team(316, "LUNATECS", "Carneys Point", "New Jersey"),
  team(321, "RoboLancers", "Philadelphia", "Pennsylvania"),
  team(341, "Miss Daisy", "Ambler", "Pennsylvania"),
  team(365, "Miracle Workerz", "Wilmington", "Delaware"),
  team(423, "Simple Machines", "Elkins Park", "Pennsylvania"),
  team(427, "LANCE-A-LOT", "Philadelphia", "Pennsylvania"),
  team(428, "BoroBlasters", "Hillsborough", "New Jersey"),
  { ...team(430, "MORT GAMMA", "Budd Lake", "New Jersey"), strengths: ["program familiarity"], weaknesses: ["verify event role"], strategyNotes: "Track as its own team for assignments and metrics." },
  team(433, "Firebirds", "Flourtown", "Pennsylvania"),
  team(484, "Roboforce", "Havertown", "Pennsylvania"),
  team(486, "Positronic Panthers", "Wallingford", "Pennsylvania"),
  team(555, "Montclair Robotics", "Montclair", "New Jersey"),
  team(708, "Hatters Robotics", "Horsham", "Pennsylvania"),
  team(709, "Femme Tech Fatale", "Bryn Mawr", "Pennsylvania"),
  team(714, "Panthera", "Newark", "New Jersey"),
  team(752, "Chargers", "Newark", "New Jersey"),
  team(816, "Anomaly", "Mount Holly", "New Jersey"),
  team(834, "SparTechs", "Center Valley", "Pennsylvania"),
  team(1089, "Team Mercury", "Hightstown", "New Jersey"),
  team(1168, "Malvern Robotics", "Malvern", "Pennsylvania"),
  team(1218, "SCH Robotics", "Philadelphia", "Pennsylvania"),
  team(1257, "Parallel Universe", "Scotch Plains", "New Jersey"),
  team(1279, "Cold Fusion", "Somerville", "New Jersey"),
  team(1391, "The Metal Moose", "West Chester", "Pennsylvania"),
  team(1403, "Team 1403 Cougar Robotics", "Skillman", "New Jersey"),
  team(1626, "Falcon Robotics", "Metuchen", "New Jersey"),
  team(1640, "Sab-BOT-age", "Downingtown", "Pennsylvania"),
  team(1647, "Iron Devils", "Tabernacle", "New Jersey"),
  team(1672, "Robo T-Birds", "Mahwah", "New Jersey"),
  team(1676, "The Pascack PI-oneers", "Montvale", "New Jersey"),
  team(1712, "Dawgma", "Ardmore", "Pennsylvania"),
  team(1807, "Redbird Robotics", "Allentown", "New Jersey"),
  team(1811, "FRESH", "Newark", "New Jersey"),
  team(1923, "The MidKnight Inventors", "Plainsboro", "New Jersey"),
  team(2016, "Mighty Monkey Wrenches", "Ewing", "New Jersey"),
  team(2095, "Direct Current", "Newtown Square", "Pennsylvania"),
  team(2180, "Zero Gravity", "Hamilton", "New Jersey"),
  team(2191, "Flux Core", "Hamilton", "New Jersey"),
  team(2234, "Alternating Current", "Newtown Square", "Pennsylvania"),
  team(2458, "Team Chaos", "Gladstone", "New Jersey"),
  team(2495, "Hive Mind", "Hamilton", "New Jersey"),
  team(2539, "Krypton Cougars", "Palmyra", "Pennsylvania"),
  team(2554, "The Warhawks", "Edison", "New Jersey"),
  team(2559, "Normality Zero", "Harrisburg", "Pennsylvania"),
  team(2577, "Pingry Robotics", "Basking Ridge", "New Jersey"),
  team(2590, "Nemesis", "Robbinsville", "New Jersey"),
  team(2607, "The Fighting RoboVikings", "Warminster", "Pennsylvania"),
  team(2720, "Red Watch Robotics", "Medford", "New Jersey"),
  team(2722, "Charge Robotics", "Marlton", "New Jersey"),
  team(3142, "Aperture", "Newton", "New Jersey"),
  team(3314, "Mechanical Mustangs", "Clifton", "New Jersey"),
  team(3340, "Union City EagleX Robotics", "Union City", "New Jersey"),
  team(3637, "The Daleks", "Flemington", "New Jersey"),
  team(4285, "Camo-Bots", "Honesdale", "Pennsylvania"),
  team(4342, "Demon Robotics", "Kennett Square", "Pennsylvania"),
  team(4361, "Roxbotix", "Roxbury Township", "New Jersey"),
  team(4573, "Rambotics", "South River", "New Jersey"),
  team(4575, "Gemini", "Media", "Pennsylvania"),
  team(4637, "BambieBotz", "Philadelphia", "Pennsylvania"),
  team(4652, "Ironmen 2", "Ramsey", "New Jersey"),
  team(4653, "Ironmen Robotics", "Ramsey", "New Jersey"),
  team(4750, "Bert", "Pennsauken", "New Jersey"),
  team(5113, "Combustible Lemons", "Moorestown", "New Jersey"),
  team(5181, "Explorer Robotics", "Wyndmoor", "Pennsylvania"),
  team(5401, "Fightin' Robotic Owls", "Bensalem", "Pennsylvania"),
  team(5407, "Wolfpack Robotics", "Conshohocken", "Pennsylvania"),
  team(5438, "Technological Terrors", "Jersey City", "New Jersey"),
  team(5490, "The Dark Byte", "Bethlehem", "Pennsylvania"),
  team(5624, "TIGER TECH Robotics", "South Plainfield", "New Jersey"),
  team(5684, "Titans of Tech", "Hamilton", "New Jersey"),
  team(5732, "ROBOTIGERS", "Bloomfield", "New Jersey"),
  team(5789, "The Other Owls", "Bensalem", "Pennsylvania"),
  team(5895, "Peddie Robotics", "Hightstown", "New Jersey"),
  team(5992, "Pirates", "West Orange", "New Jersey"),
  team(6016, "Tiger Robotics", "Hackettstown", "New Jersey"),
  team(6226, "Blue Devils", "Burlington", "New Jersey"),
  team(6808, "William Tennent Robotics", "Warminster", "Pennsylvania"),
  team(6860, "Equitum Robotics", "Paterson", "New Jersey"),
  team(6897, "Astraea Robotics", "East Brunswick", "New Jersey"),
  team(6921, "Technados", "Pennsauken", "New Jersey"),
  team(6945, "Children of the Corn", "Blairstown", "New Jersey"),
  team(7045, "MCCrusaders", "Denville", "New Jersey"),
  team(7110, "Heights Bytes", "Haddon Heights", "New Jersey"),
  team(7414, "Retrobotics", "Collegeville", "Pennsylvania"),
  team(7587, "Metuchen Momentum", "Metuchen", "New Jersey"),
  team(8075, "CyberTigers", "Dover", "New Jersey"),
  team(8117, "Easton RoboRovers", "Easton", "Pennsylvania"),
  team(8130, "Absegami Robotics", "Absecon", "New Jersey"),
  team(8513, "Sisters 1st", "Morristown", "New Jersey"),
  team(8588, "Tech Devils", "Denville", "New Jersey"),
  team(8628, "Newark School of Global Studies", "Newark", "New Jersey"),
  team(8630, "CAP ROBOTICS", "Paterson", "New Jersey"),
  team(8704, "Void Warranty", "Cape May", "New Jersey"),
  team(8706, "MXS Bulldog Bots", "Newark", "New Jersey"),
  team(8707, "The Newark Circuit Breakers", "Newark", "New Jersey"),
  team(8714, "Robo Griffins'", "Toms River", "New Jersey"),
  team(8721, "Code Name M.I.T.", "Cape May Court House", "New Jersey"),
  team(8771, "PioTech", "Wayne", "New Jersey"),
  team(9014, "Vulcan Mechanics", "Philadelphia", "Pennsylvania"),
  team(9015, "Questionable Engineering", "Jersey City", "New Jersey"),
  team(9027, "PATH to Domination", "Norristown", "Pennsylvania"),
  team(9094, "The Earthquakers", "Wynnewood", "Pennsylvania"),
  team(9100, "Robo Roses", "Belmar", "New Jersey"),
  team(9116, "The Canucks & Bolts", "North Plainfield", "New Jersey"),
  team(9416, "International Operatives of World Affairs", "Philadelphia", "Pennsylvania"),
  team(9424, "E.O. JAG BOTS", "East Orange", "New Jersey"),
  team(9439, "Knights of Polaris", "Newark", "New Jersey"),
  team(10070, "Ghost Bots", "Abington", "Pennsylvania"),
  team(10143, "Northeast Vikings", "Philadelphia", "Pennsylvania"),
  team(10157, "Roman Robotics", "Philadelphia", "Pennsylvania"),
  team(10170, "ND Robotics", "Lawrence Township", "New Jersey"),
  team(10232, "Killer Kardinals 2", "Plainfield", "New Jersey"),
  team(10366, "Builder Bears", "Bergenfield", "New Jersey"),
  team(10400, "DART Doane Academy Robotics Team", "Burlington", "New Jersey"),
  team(10584, "Ridge Robotics", "Perkasie", "Pennsylvania"),
  team(10600, "Two Steps Ahead", "Edison", "New Jersey"),
  team(10918, "Bluesteel Dragons", "Philadelphia", "Pennsylvania"),
  team(10949, "Metalheads", "Philadelphia", "Pennsylvania"),
  team(10979, "Tiger Robotics", "Philadelphia", "Pennsylvania"),
  team(10989, "Blast Robotics", "Berwyn", "Pennsylvania"),
  team(10993, "EP Robotics", "Enola", "Pennsylvania"),
  team(10995, "ACS Eagle Robotics", "Rockaway", "New Jersey"),
  team(10997, "St. George", "Jersey City", "New Jersey"),
  team(11104, "Phoenix Phanatics", "East Brunswick", "New Jersey"),
  team(11225, "Wolfimus", "Camden", "New Jersey"),
  team(11366, "Red Devil's Redemption", "West Grove", "Pennsylvania")
];

export const matches: Match[] = [
  { id: "qm1", number: 1, time: "2026-03-06T09:10:00-05:00", red: [11, 25, 56], blue: [75, 102, 303], redScore: 116, blueScore: 108 },
  { id: "qm2", number: 2, time: "2026-03-06T09:22:00-05:00", red: [193, 430, 2590], blue: [341, 365, 708], redScore: 121, blueScore: 129 },
  { id: "qm3", number: 3, time: "2026-03-06T09:34:00-05:00", red: [11, 103, 1403], blue: [1676, 1923, 2016], redScore: 134, blueScore: 126 },
  { id: "qm4", number: 4, time: "2026-03-06T09:46:00-05:00", red: [272, 293, 1089], blue: [2590, 3314, 5895], redScore: 112, blueScore: 137 },
  { id: "qm5", number: 5, time: "2026-03-06T09:58:00-05:00", red: [11, 25, 193], blue: [341, 2590, 1676] }
];

const entry = (matchNumber: number, teamNumber: number, alliance: "red" | "blue", auto: [number, number], tele: [number, number], climb: string, defense: number, skill: number, cycles: number[], flags: Partial<MatchScoutEntry> = {}): MatchScoutEntry => ({
  id: `m${matchNumber}-${teamNumber}`,
  eventId: event.id,
  matchId: `qm${matchNumber}`,
  matchNumber,
  teamNumber,
  alliance,
  station: `${alliance.toUpperCase()} ${((matchNumber + teamNumber) % 3) + 1}`,
  scoutName: ["Avery", "Sam", "Jordan", "Riley"][teamNumber % 4],
  autoFuelMade: auto[0],
  autoFuelAttempted: auto[1],
  teleFuelMade: tele[0],
  teleFuelAttempted: tele[1],
  intakeSource: teamNumber % 2 ? "Ground" : "Both",
  cycleTimes: cycles,
  towerClimbLevel: climb,
  climbSuccess: climb !== "None" && climb !== "Park",
  defenseRating: defense,
  driverSkill: skill,
  penalties: 0,
  fouls: teamNumber === 2590 ? 1 : 0,
  disabled: false,
  tipped: false,
  connectionIssues: false,
  breakdowns: "",
  quickNotes: skill >= 5 ? ["Fast cycles", "Great driver"] : defense >= 4 ? ["Strong defense"] : ["Clean intake"],
  notes: "",
  createdAt: new Date().toISOString(),
  synced: true,
  ...flags
});

export const matchEntries: MatchScoutEntry[] = [
  entry(1, 11, "red", [6, 8], [24, 32], "High Tower", 2, 5, [17, 18, 18, 19]),
  entry(1, 25, "red", [4, 7], [19, 27], "Mid Tower", 3, 4, [21, 22, 23]),
  entry(1, 56, "red", [3, 5], [13, 22], "High Tower", 2, 4, [26, 25, 24]),
  entry(1, 75, "blue", [5, 7], [20, 29], "Mid Tower", 3, 4, [20, 21, 22]),
  entry(1, 102, "blue", [4, 6], [18, 25], "High Tower", 2, 4, [22, 23, 21]),
  entry(1, 303, "blue", [6, 8], [21, 30], "Park", 4, 4, [19, 20, 21]),
  entry(2, 193, "red", [4, 6], [16, 24], "Mid Tower", 3, 4, [23, 24, 25]),
  entry(2, 430, "red", [3, 5], [14, 22], "Low Tower", 2, 3, [26, 28]),
  entry(2, 2590, "red", [8, 10], [27, 34], "High Tower", 3, 5, [15, 16, 17, 16]),
  entry(2, 341, "blue", [7, 9], [26, 33], "Traversal Tower", 2, 5, [16, 17, 16, 18]),
  entry(2, 365, "blue", [6, 8], [22, 31], "High Tower", 2, 4, [18, 19, 20, 18]),
  entry(2, 708, "blue", [4, 6], [17, 24], "Mid Tower", 3, 4, [22, 23, 24]),
  entry(3, 11, "red", [7, 9], [28, 35], "High Tower", 2, 5, [16, 17, 16, 17, 18]),
  entry(3, 103, "red", [5, 7], [20, 28], "Mid Tower", 2, 4, [21, 22, 22]),
  entry(3, 1403, "red", [4, 6], [18, 26], "High Tower", 3, 4, [22, 21, 23]),
  entry(3, 1676, "blue", [7, 10], [25, 33], "High Tower", 2, 5, [17, 18, 17, 19]),
  entry(3, 1923, "blue", [6, 8], [23, 31], "Mid Tower", 2, 5, [18, 19, 18, 20]),
  entry(3, 2016, "blue", [3, 5], [16, 24], "Low Tower", 4, 4, [24, 25, 26]),
  entry(4, 272, "red", [5, 7], [19, 27], "Mid Tower", 3, 4, [21, 22, 23]),
  entry(4, 293, "red", [4, 6], [17, 26], "High Tower", 2, 4, [23, 22, 24]),
  entry(4, 1089, "red", [5, 8], [20, 29], "Park", 3, 4, [21, 22, 22]),
  entry(4, 2590, "blue", [9, 11], [30, 37], "High Tower", 3, 5, [14, 15, 16, 15], { fouls: 1 }),
  entry(4, 3314, "blue", [6, 8], [24, 32], "Traversal Tower", 2, 5, [17, 18, 18, 17]),
  entry(4, 5895, "blue", [4, 6], [18, 25], "Mid Tower", 2, 4, [22, 23, 24])
];

export const pitEntries: PitScoutEntry[] = teams.map((team, index) => ({
  id: `pit-${team.number}`,
  eventId: event.id,
  teamNumber: team.number,
  scoutName: ["Morgan", "Taylor", "Casey"][index % 3],
  drivetrain: index % 3 === 0 ? "Swerve" : index % 3 === 1 ? "West Coast" : "Tank",
  weightLbs: 110 + (index % 5) * 4,
  frameLengthIn: 28,
  frameWidthIn: 28 + (index % 2) * 2,
  mechanisms: index % 2 ? ["over-bumper intake", "adjustable shooter", "single-stage climb"] : ["wide intake", "fixed hub shooter", "double-stage climb"],
  climbAbility: defaultGameConfig.scoringFields.climb.levels[2 + (index % 4)],
  scoringLevels: ["Hub close", "Hub far", "Auto preload"],
  autoPaths: index % 2 ? ["taxi + 5 fuel", "center pickup"] : ["taxi + 3 fuel", "source side pickup"],
  driveTeamComments: "Initial FMA profile imported from regional team list. Replace with pit interview notes at the event.",
  reliability: 3 + (index % 3),
  repairNotes: "No event-specific repair notes yet.",
  archetypes: index % 4 === 0 ? ["scorer", "climber"] : index % 4 === 1 ? ["hybrid"] : index % 4 === 2 ? ["defender", "support bot"] : ["scorer"],
  photos: [],
  createdAt: new Date().toISOString()
}));
